version: '3.8'

services:
  library:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - JWT_SECRET=secret
      - JWT_EXPIRATIONINMS=20000000
      - SPRINGDOC_SWAGGER_UI_ENABLED=true
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui.html
      - SPRINGDOC_API_DOCS_PATH=/api-docs